// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: message/account.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//用于调试的登陆接口，线上会关闭
type C2S_Login_DEBUG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      //用户id
	ClientId string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` //
}

func (x *C2S_Login_DEBUG) Reset() {
	*x = C2S_Login_DEBUG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Login_DEBUG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login_DEBUG) ProtoMessage() {}

func (x *C2S_Login_DEBUG) ProtoReflect() protoreflect.Message {
	mi := &file_message_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login_DEBUG.ProtoReflect.Descriptor instead.
func (*C2S_Login_DEBUG) Descriptor() ([]byte, []int) {
	return file_message_account_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_Login_DEBUG) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *C2S_Login_DEBUG) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// 服务端响应收到的请求
type S2C_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   //用户id
	Nick         string    `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`                                      //用户昵称
	Avatar       string    `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                  //头像URL 只在玩家设置为渠道头像来源是存在
	AvatarSource uint32    `protobuf:"varint,4,opt,name=avatar_source,json=avatarSource,proto3" json:"avatar_source,omitempty"` //选择的头像源 0 默认头像、1 渠道头像、2 系统头像
	SystemAvatar string    `protobuf:"bytes,5,opt,name=system_avatar,json=systemAvatar,proto3" json:"system_avatar,omitempty"`  //系统头像ID
	Lang         string    `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang,omitempty"`                                      //语言
	AgoraToken   string    `protobuf:"bytes,7,opt,name=AgoraToken,proto3" json:"AgoraToken,omitempty"`                          // 声网token
	Code         ErrorCode `protobuf:"varint,8,opt,name=Code,proto3,enum=error.ErrorCode" json:"Code,omitempty"`                // 后端业务员错误码
	Message      string    `protobuf:"bytes,9,opt,name=Message,proto3" json:"Message,omitempty"`                                // 错误信息
}

func (x *S2C_Login) Reset() {
	*x = S2C_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Login) ProtoMessage() {}

func (x *S2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_message_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Login.ProtoReflect.Descriptor instead.
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return file_message_account_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_Login) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2C_Login) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *S2C_Login) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *S2C_Login) GetAvatarSource() uint32 {
	if x != nil {
		return x.AvatarSource
	}
	return 0
}

func (x *S2C_Login) GetSystemAvatar() string {
	if x != nil {
		return x.SystemAvatar
	}
	return ""
}

func (x *S2C_Login) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *S2C_Login) GetAgoraToken() string {
	if x != nil {
		return x.AgoraToken
	}
	return ""
}

func (x *S2C_Login) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_Success
}

func (x *S2C_Login) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_message_account_proto protoreflect.FileDescriptor

var file_message_account_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x1a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x8e,
	0x02, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x67, 0x6f, 0x72, 0x61, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x67, 0x6f, 0x72, 0x61, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x24, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x75,
	0x78, 0x69, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_account_proto_rawDescOnce sync.Once
	file_message_account_proto_rawDescData = file_message_account_proto_rawDesc
)

func file_message_account_proto_rawDescGZIP() []byte {
	file_message_account_proto_rawDescOnce.Do(func() {
		file_message_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_account_proto_rawDescData)
	})
	return file_message_account_proto_rawDescData
}

var file_message_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_account_proto_goTypes = []interface{}{
	(*C2S_Login_DEBUG)(nil), // 0: account.C2S_Login_DEBUG
	(*S2C_Login)(nil),       // 1: account.S2C_Login
	(ErrorCode)(0),          // 2: error.ErrorCode
}
var file_message_account_proto_depIdxs = []int32{
	2, // 0: account.S2C_Login.Code:type_name -> error.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_account_proto_init() }
func file_message_account_proto_init() {
	if File_message_account_proto != nil {
		return
	}
	file_message_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Login_DEBUG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_account_proto_goTypes,
		DependencyIndexes: file_message_account_proto_depIdxs,
		MessageInfos:      file_message_account_proto_msgTypes,
	}.Build()
	File_message_account_proto = out.File
	file_message_account_proto_rawDesc = nil
	file_message_account_proto_goTypes = nil
	file_message_account_proto_depIdxs = nil
}
