// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: message/response.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 服务端响应收到的请求
type S2C_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trace  string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`   //请求跟踪ID
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   //当请求异常时的错误信息，如请求正常该值是一个空字符串""
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` //响应内容,根据不同的业务类型需要做解析
}

func (x *S2C_Response) Reset() {
	*x = S2C_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Response) ProtoMessage() {}

func (x *S2C_Response) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Response.ProtoReflect.Descriptor instead.
func (*S2C_Response) Descriptor() ([]byte, []int) {
	return file_message_response_proto_rawDescGZIP(), []int{0}
}

func (x *S2C_Response) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *S2C_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *S2C_Response) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// 默认的业务层响应格式
type DefaultResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                        //code码 0 代表成功 非零代表业务异常
	ErrorMsg string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` //业务处理异常处理码
}

func (x *DefaultResult) Reset() {
	*x = DefaultResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResult) ProtoMessage() {}

func (x *DefaultResult) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResult.ProtoReflect.Descriptor instead.
func (*DefaultResult) Descriptor() ([]byte, []int) {
	return file_message_response_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultResult) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DefaultResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_message_response_proto protoreflect.FileDescriptor

var file_message_response_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x52, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x40, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x75, 0x78, 0x69, 0x61, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_response_proto_rawDescOnce sync.Once
	file_message_response_proto_rawDescData = file_message_response_proto_rawDesc
)

func file_message_response_proto_rawDescGZIP() []byte {
	file_message_response_proto_rawDescOnce.Do(func() {
		file_message_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_proto_rawDescData)
	})
	return file_message_response_proto_rawDescData
}

var file_message_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_response_proto_goTypes = []interface{}{
	(*S2C_Response)(nil),  // 0: response.S2C_Response
	(*DefaultResult)(nil), // 1: response.DefaultResult
}
var file_message_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_response_proto_init() }
func file_message_response_proto_init() {
	if File_message_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_proto_goTypes,
		DependencyIndexes: file_message_response_proto_depIdxs,
		MessageInfos:      file_message_response_proto_msgTypes,
	}.Build()
	File_message_response_proto = out.File
	file_message_response_proto_rawDesc = nil
	file_message_response_proto_goTypes = nil
	file_message_response_proto_depIdxs = nil
}
